"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Invoice } from "@/lib/types";
import { getInvoice } from "@/lib/db";

export default function InvoiceDetailPage() {
  const params = useParams();
  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const inv = getInvoice(params.id as string);
    setInvoice(inv || null);
    setLoading(false);
  }, [params.id]);

  const downloadPDF = async () => {
    // Dynamic import for client-side only
    const { jsPDF } = await import("jspdf");
    await import("jspdf-autotable");

    if (!invoice) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header — Sender info (upper left)
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text(invoice.senderName || "Your Business", 20, 20);
    let senderY = 26;
    if (invoice.senderAddress) {
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      const addrLines = doc.splitTextToSize(invoice.senderAddress, 80);
      doc.text(addrLines, 20, senderY);
      senderY += addrLines.length * 4.5;
    }

    // Invoice title (upper right)
    doc.setFontSize(24);
    doc.setTextColor(30, 30, 30);
    doc.text("INVOICE", pageWidth - 20, 20, { align: "right" });

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(invoice.invoiceNumber, pageWidth - 20, 28, { align: "right" });
    doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, pageWidth - 20, 34, { align: "right" });
    doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, pageWidth - 20, 40, { align: "right" });

    // Bill To
    const billToY = Math.max(senderY + 10, 52);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Bill To:", 20, billToY);
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.text(invoice.clientName, 20, billToY + 8);
    if (invoice.clientEmail) {
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(invoice.clientEmail, 20, billToY + 14);
    }

    // Table
    const tableData = invoice.items.map((item) => {
      const qty = item.kind === "service" ? 1 : item.quantity;
      return [
        item.description,
        item.kind === "service" ? "—" : item.quantity.toString(),
        `$${item.rate.toFixed(2)}`,
        `$${(qty * item.rate).toFixed(2)}`,
      ];
    });

    (doc as any).autoTable({
      startY: 70,
      head: [["Description", "Qty", "Rate", "Amount"]],
      body: tableData,
      theme: "plain",
      headStyles: {
        fillColor: [245, 245, 245],
        textColor: [60, 60, 60],
        fontStyle: "bold",
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [40, 40, 40],
      },
      columnStyles: {
        0: { cellWidth: "auto" },
        1: { halign: "center", cellWidth: 25 },
        2: { halign: "right", cellWidth: 30 },
        3: { halign: "right", cellWidth: 35 },
      },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 15;

    // Totals
    const rightX = pageWidth - 20;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Subtotal:", rightX - 50, finalY);
    doc.text(`$${invoice.subtotal.toFixed(2)}`, rightX, finalY, { align: "right" });

    if (invoice.taxRate > 0) {
      doc.text(`Tax (${invoice.taxRate}%):`, rightX - 50, finalY + 7);
      doc.text(`$${invoice.tax.toFixed(2)}`, rightX, finalY + 7, { align: "right" });
    }

    doc.setFontSize(13);
    doc.setTextColor(30, 30, 30);
    const totalY = invoice.taxRate > 0 ? finalY + 18 : finalY + 10;
    doc.text("Total:", rightX - 50, totalY);
    doc.text(`$${invoice.total.toFixed(2)}`, rightX, totalY, { align: "right" });

    // Notes
    if (invoice.notes) {
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text("Notes:", 20, totalY + 20);
      doc.text(invoice.notes, 20, totalY + 27, { maxWidth: pageWidth - 40 });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text("Generated by BillFlow", pageWidth / 2, 285, { align: "center" });

    doc.save(`${invoice.invoiceNumber}.pdf`);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center text-zinc-500">
        Loading...
      </div>
    );
  }

  if (!invoice) {
    return (
      <div className="min-h-screen flex items-center justify-center text-zinc-500">
        Invoice not found.
      </div>
    );
  }

  const statusColors: Record<string, string> = {
    draft: "bg-zinc-700 text-zinc-300",
    sent: "bg-yellow-900/50 text-yellow-400",
    paid: "bg-green-900/50 text-green-400",
  };

  return (
    <div className="min-h-screen">
      <nav className="border-b border-zinc-800 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="text-xl font-bold tracking-tight">
          <span className="text-white">Bill</span>
          <span className="text-blue-500">Flow</span>
        </Link>
        <div className="flex items-center gap-3">
          <button
            onClick={downloadPDF}
            className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-500 transition-colors"
          >
            Download PDF
          </button>
          <Link
            href="/invoices"
            className="text-sm text-zinc-400 hover:text-white transition-colors"
          >
            ← Back
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-10">
        {/* Invoice Preview */}
        <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-8 space-y-8">
          {/* Header */}
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold tracking-tight">INVOICE</h1>
              <p className="text-sm text-zinc-500 font-mono mt-1">
                {invoice.invoiceNumber}
              </p>
            </div>
            <span className={`rounded-full px-3 py-1 text-xs font-medium ${statusColors[invoice.status]}`}>
              {invoice.status}
            </span>
          </div>

          {/* From / To */}
          <div className="grid grid-cols-2 gap-8">
            <div className="space-y-1">
              <p className="text-xs text-zinc-500 uppercase tracking-wider">From</p>
              <p className="font-medium">{invoice.senderName}</p>
              {invoice.senderAddress && (
                <p className="text-sm text-zinc-400 whitespace-pre-wrap">{invoice.senderAddress}</p>
              )}
            </div>
            <div className="space-y-1 text-right">
              <p className="text-xs text-zinc-500 uppercase tracking-wider">Details</p>
              <p className="text-sm text-zinc-400">
                Created: {new Date(invoice.createdAt).toLocaleDateString()}
              </p>
              <p className="text-sm text-zinc-400">
                Due: {new Date(invoice.dueDate).toLocaleDateString()}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-8">
            <div className="space-y-1">
              <p className="text-xs text-zinc-500 uppercase tracking-wider">Bill To</p>
              <p className="font-medium">{invoice.clientName}</p>
              {invoice.clientEmail && (
                <p className="text-sm text-zinc-400">{invoice.clientEmail}</p>
              )}
            </div>
          </div>

          {/* Items Table */}
          <div className="overflow-hidden rounded-lg border border-zinc-800">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-zinc-800/50">
                  <th className="px-4 py-3 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">
                    Description
                  </th>
                  <th className="px-4 py-3 text-center text-xs font-medium text-zinc-400 uppercase tracking-wider">
                    Qty
                  </th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-zinc-400 uppercase tracking-wider">
                    Rate
                  </th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-zinc-400 uppercase tracking-wider">
                    Amount
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800">
                {invoice.items.map((item) => {
                  const qty = item.kind === "service" ? 1 : item.quantity;
                  return (
                    <tr key={item.id}>
                      <td className="px-4 py-3">{item.description}</td>
                      <td className="px-4 py-3 text-center tabular-nums">
                        {item.kind === "service" ? "—" : item.quantity}
                      </td>
                      <td className="px-4 py-3 text-right tabular-nums">${item.rate.toFixed(2)}</td>
                      <td className="px-4 py-3 text-right tabular-nums">
                        ${(qty * item.rate).toFixed(2)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Totals */}
          <div className="flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-sm text-zinc-400">
                <span>Subtotal</span>
                <span className="tabular-nums">${invoice.subtotal.toFixed(2)}</span>
              </div>
              {invoice.taxRate > 0 && (
                <div className="flex justify-between text-sm text-zinc-400">
                  <span>Tax ({invoice.taxRate}%)</span>
                  <span className="tabular-nums">${invoice.tax.toFixed(2)}</span>
                </div>
              )}
              <div className="flex justify-between text-xl font-bold pt-3 border-t border-zinc-700">
                <span>Total</span>
                <span className="tabular-nums">${invoice.total.toFixed(2)}</span>
              </div>
            </div>
          </div>

          {/* Notes */}
          {invoice.notes && (
            <div className="pt-4 border-t border-zinc-800">
              <p className="text-xs text-zinc-500 uppercase tracking-wider mb-2">Notes</p>
              <p className="text-sm text-zinc-400 whitespace-pre-wrap">{invoice.notes}</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
